//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.10 at 10:19:18 AM EST 
//


package au.com.fowles.local.wmdev02_is8_sandpit.zzabhi.call1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vehicleGroup" type="{http://wmdev02-is8-sandpit.local.fowles.com.au/zzAbhi/Call1}vehicleGroup"/>
 *         &lt;element name="sequence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getInput", propOrder = {
    "vehicleGroup",
    "sequence"
})
public class GetInput {

    @XmlElement(required = true, nillable = true)
    protected VehicleGroup vehicleGroup;
    @XmlElementRef(name = "sequence", type = JAXBElement.class)
    protected JAXBElement<String> sequence;

    /**
     * Gets the value of the vehicleGroup property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleGroup }
     *     
     */
    public VehicleGroup getVehicleGroup() {
        return vehicleGroup;
    }

    /**
     * Sets the value of the vehicleGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleGroup }
     *     
     */
    public void setVehicleGroup(VehicleGroup value) {
        this.vehicleGroup = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSequence(JAXBElement<String> value) {
        this.sequence = ((JAXBElement<String> ) value);
    }

}
