AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Instances for ULTRA-VR in the Production Environment

Parameters:
  ImageId:
    Type: String
    Description: AMI Id
    Default: ami-0d52d93f5d72435cf

  ShortBusinessServiceCI:
    Type: String
    Default: Test

Mappings:
  Subnets:
    Private:
      A: subnet-0998b21ffd55bdf1f
Resources:
  Test1nic0:
    Properties:
      SubnetId: !FindInMap [ Subnets,Private,A ]
      GroupSet:
        - sg-0096c4af11e4b932b
      Tags:
        - Key: Name
          Value:  tcpaws-ivrco1-002-verint-int-mdl01-ULTRA-VR-prd-Test1-nic0 
    Type: 'AWS::EC2::NetworkInterface'
  Test1:
    Properties:
      KeyName: tcpaws-ivrco1-002-verint-int-mdl01-iamr-ultra-vr-prod-loginpolicy
      ImageId: ami-0d52d93f5d72435cf
      InstanceType: c5.9xlarge
      IamInstanceProfile: tcpaws-ivrco1-002-verint-int-mdl01-iamr-ultra-vr-prod-iamapprole
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            DeleteOnTermination: true
            Encrypted: yes
            KmsKeyId: cd7061d6-3294-45ba-87b6-3acef238c245
            VolumeSize: 100
        - DeviceName: /dev/sdb
          Ebs:
            VolumeType: gp2
            DeleteOnTermination: true
            Encrypted: yes
            KmsKeyId: cd7061d6-3294-45ba-87b6-3acef238c245
            VolumeSize: 100
        - DeviceName: /dev/sdc
          Ebs:
            VolumeType: gp2
            DeleteOnTermination: true
            Encrypted: yes
            KmsKeyId: cd7061d6-3294-45ba-87b6-3acef238c245
            VolumeSize: 2000       
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref Test1nic0
          DeleteOnTermination: false
          DeviceIndex: 0
          Description: >-
            eni for Test1 ec2 instance, used by b2bautomation in
            the prd environment
      Tags:
        - Key: Name
          Value: tcpaws-ivrco1-002-verint-int-mdl01-ULTRA-VR-prd-Test1
        - Key: SecurityTierClass
          Value: application
        - Key: SecurityTierName
          Value: Appserver
        - Key: BusinessUnit
          Value: Digital Transformation
        - Key: BusinessServiceCI
          Value: ULTRA-VR
        - Key: EnvironmentType
          Value: prod
        - Key: EnvironmentName
          Value: prd
        - Key: AssetCI
          Value: !Join 
            - '-'
            - - !Ref ShortBusinessServiceCI
              - prd
              - 1
        - Key: SecurityTierClass
          Value: application
        - Key: SecurityTierName
          Value: Appserver
      DisableApiTermination: false
      InstanceInitiatedShutdownBehavior: stop
    Type: 'AWS::EC2::Instance'
