//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.10 at 10:19:18 AM EST 
//


package au.com.fowles.local.wmdev02_is8_sandpit.zzabhi.call1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getOutput" type="{http://wmdev02-is8-sandpit.local.fowles.com.au/zzAbhi/Call1}getOutput"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getResponse", propOrder = {
    "getOutput"
})
public class GetResponse {

    @XmlElement(required = true, nillable = true)
    protected GetOutput getOutput;

    /**
     * Gets the value of the getOutput property.
     * 
     * @return
     *     possible object is
     *     {@link GetOutput }
     *     
     */
    public GetOutput getGetOutput() {
        return getOutput;
    }

    /**
     * Sets the value of the getOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetOutput }
     *     
     */
    public void setGetOutput(GetOutput value) {
        this.getOutput = value;
    }

}
