//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.10 at 10:19:18 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://wmdev02-is8-sandpit.local.fowles.com.au/zzAbhi/Call1")
package au.com.fowles.local.wmdev02_is8_sandpit.zzabhi.call1;
