version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=http://local.test.pearsonplaces.com.au:4200, http://intstaging.lightbook.pearsonplaces.com.au, http://lightbook.pearsonplaces.com.au, http://staging1.lightbook.pearsonplaces.com.au
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1g
    ports:
      - 9200:9200
    networks:
      - lnet
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    container_name: kibana
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=changeme"  
      - "ELASTICSEARCH_URL=http://elasticsearch1:9200"
      - "NODE_OPTIONS=--max-old-space-size=200"
    ports:
      - 5601:5601
    links:
      - elasticsearch1
    networks:
      - lnet
  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.2
    container_name: logstash
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - path.config=/usr/share/logstash/pipeline
      - xpack.monitoring.elasticsearch.url=http://elasticsearch1:9200
      - xpack.monitoring.elasticsearch.password=changeme
      - xpack.monitoring.elasticsearch.username=elastic
    ports:
      - 5000:5000
    command: logstash -e 'input { gelf { port => 5000 } } output { elasticsearch { hosts => ["elasticsearch1:9200"] } stdout { codec => rubydebug } }' -f /usr/share/logstash/config/logstash.conf
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./tmp:/usr/share/logstash/tmp
    links:
      - elasticsearch1
      - kibana      
    networks:
      - lnet
      
networks:
  lnet:
   driver: bridge  